---
title: "Plots developed by Aira Contreras"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## List of Figures to Reproduce


```{r}
#loading library to enable visualization of ggplot function use
library(ggplot2)
library(ggrepel)
```

### Mean Frequency of Risky Choices (Random MF)
```{r}

names<-rep(c("Dara","Rita","Liza", "Azalea", "Barbi","Rowena","Katie","Fiona"), each=2)
lnames<-c("","Dara","","Rita","","Liza", "","Azalea", "","Barbi","","Rowena","","Katie","","Fiona")
mean_frequency<-rnorm(16,45,25)
condition<-rep(c("Social Condition","Nonsocial Condition"),8)
adversity<-rep(c("Adverse","Not_Adverse"),times=c(4,4))

plot_df<-data.frame(names,mean_frequency,adversity,condition)

#print(plot_df)

b<-ggplot(plot_df, aes(condition,mean_frequency,group=names,linetype=adversity))+geom_line()+geom_text_repel(label=lnames, position = "nudge")+theme_classic()

b+labs(x="",y="Mean Frequency of Risky Choice")+theme(legend.position = "none")+scale_y_continuous(breaks = pretty(0:70,n=7))
```

### Mean Frequency of Risky Choices (Data Duplicat of Assignment Attempt)
```{r}

names<-rep(c("Dara","Rita","Liza", "Azalea", "Barbi","Rowena","Katie","Fiona"), each=2)
lnames<-c("","Dara","","Rita","","Liza", "","Azalea", "","Barbi","","Rowena","","Katie","","Fiona")
mean_frequency<-floor(runif(16,0,70))
condition<-rep(c("Social Condition","Nonsocial Condition"),8)
adversity<-rep(c("Adverse","Not_Adverse"),times=c(4,4))

plot_df<-data.frame(names,mean_frequency,adversity,condition)

#print(plot_df)

a<-ggplot(plot_df, aes(condition,mean_frequency,group=names,linetype=adversity))+geom_line()+geom_text_repel(label=lnames, position = "nudge")+theme_classic()

a+theme(legend.position = "none")+labs(x="",y="Mean Frequency of Risky Choice")+theme(legend.position = "none")+scale_y_continuous(breaks = pretty(0:70,n=7))
```

### Average Frequency of Social Risks

```{r}
avg_nonsoc<-c(0,60)
avg_soc<-c(25,65)
ad_avg_nonsoc<-c(0,0,2,5,9,30,52,57,67)
ad_avg_soc<-c(0,12,48,4,41,48,33,57,59)
plot_da<-data.frame(avg_nonsoc,avg_soc)
plot_db<-data.frame(ad_avg_nonsoc,ad_avg_soc)

c<-ggplot(plot_da)+geom_line(mapping = aes(avg_nonsoc,avg_soc))+geom_point(data =plot_db ,x=ad_avg_nonsoc,y=ad_avg_soc, size=1)+theme_classic()+coord_cartesian(xlim = c(0,70),ylim = c(0,70),clip = "off")


c+labs(x="Average Frequency of Nonsocial Risk",y="Average Frequency of Social Risk")+scale_x_continuous(expand = c(0,0),breaks = pretty(0:70,n=7))+scale_y_continuous(expand = c(0,0),breaks = pretty(0:70,n=7))
```

### Cup Bar Graph (Wide Base/Wide Top)
```{r}
nums<-runif(100,17,20)
cat<-as.factor(rep(c("Fill","Empty"),each=15,len=100))
base<-as.factor(rep(c("Wide Base","Wide Top"),each=45,len=100))
plot_dd<-data.frame(nums,cat,base)
f_mean<-rep(c(19.5,19.8,19.4,19.9,19.1),len=100)
f_se<-rep(c(.1,.1,.1,.1,.1),len=100)

ggplot(plot_dd,aes(cat,nums,group=base,color=base,fill=base))+geom_bar(stat = "identity",position = "dodge")+coord_cartesian(ylim = c(17,20))+geom_errorbar(aes(ymin=f_mean-f_se,ymax=f_mean+f_se),width=.2,position = position_dodge(width = 0.9),color="black")
```

### Cup Bar Graph (Wide Base/Wide Top)--Error Bars Test
```{r}
#I understand that the issue here is that the means are not being separately calculated for each subset--will attempt to correct this, but will try another chart type first.
nums<-runif(10,17,20)
cat<-as.factor(rep(c("Fill","Empty"),each=5,len=10))
base<-as.factor(rep(c("Wide Base","Wide Top"),each=3,len=10))
f_mean<-rep(mean(nums),len=10)
f_se<-rep((sd(nums)^2),len=10)
plot_dd<-data.frame(nums,cat,base,f_mean,f_se)

e<-ggplot(plot_dd,aes(cat,nums,group=base,color=base,fill=base))+geom_bar(stat = "identity",position = "dodge")+coord_cartesian(ylim = c(17,20))+geom_errorbar(aes(ymin=f_mean-f_se,ymax=f_mean+f_se),width=.2,position = position_dodge(width = 0.9),color="black")+theme_classic()

e+theme(legend.position = "top")+scale_y_continuous(breaks = pretty(17:20,n=7))
```

### Evaluation of Person X

```{r}

pvaluesM<-floor(runif(100,80,95))
pvaluesF<-floor(runif(100,45,90))                
evaluesM<-rep(1:7,len=100)
evaluesF<-rep(1:7,len=100)
pvaluesc<-c(pvaluesM,pvaluesF)
evaluesc<-c(evaluesM,evaluesF)
sex<-as.factor(rep(c("Male","Female"),each=100))
plot_de<-data.frame(pvaluesc,evaluesc,sex)

f<-ggplot(plot_de)+geom_smooth(mapping=aes(evaluesc,pvaluesc,linetype=sex))+theme_classic()

f+theme(legend.position = "bottom")+labs(ylab="P(Target=Pilot)",xlab="Evaluation of Person X")
```

